import { createHash } from "node:crypto"
import { prisma } from "@dilirik/db"
import {
  curateTopPicks,
  generateSearchProfile,
  ruleBasedScore,
  summarizeProfile,
  type CurationCandidate,
} from "@dilirik/ai"
import {
  DISCOVERY_CANDIDATE_LIMIT,
  DISCOVERY_CURATION_INPUT,
  DISCOVERY_OTHER_CANDIDATES,
  DISCOVERY_PROMPT_VERSION,
  DISCOVERY_RELAX_THRESHOLD,
  DISCOVERY_STALE_DAYS,
  DISCOVERY_TOP_PICKS,
  type DiscoveryRunListItemDto,
  type DiscoverySearchInput,
  type DiscoverySearchResponse,
  type DiscoveryStatusDto,
  type DismissJobMatchInput,
  type JobMatchDto,
  type JobSourceDto,
  type SearchProfileDto,
  type SearchProfileOverrides,
  type UpdateSearchProfileInput,
} from "@dilirik/shared"
import { HttpError } from "../middleware/errorHandler.js"
import { checkDiscoveryEntitlement, consumeDiscoveryQuota } from "./discoveryQuota.js"
import { getIndexAgeHours } from "./ingestionService.js"

/**
 * Service Cari Lowongan (PRD Cari Lowongan §10–§12).
 *
 * Alur satu pencarian:
 *   kuota → profil pencarian (cache per versi CV) → ambil kandidat dari indeks
 *   lokal → skor rule-based (gratis) → SATU call LLM untuk 5 "Wajib Coba"
 *   → simpan run + match.
 *
 * Dua hal yang dijaga ketat di sini:
 * 1. Tidak ada call ke sumber eksternal. Pencarian membaca indeks, titik.
 * 2. Skor di halaman ini adalah "perkiraan cocok" — BUKAN skor analisis. Analisis
 *    penuh tetap memakai kuota analisis lewat alur yang sudah ada.
 */

const MS_PER_DAY = 86_400_000
const MS_PER_HOUR = 3_600_000

const SENIORITY_ORDER = ["entry", "mid", "senior", "lead"] as const
type Seniority = (typeof SENIORITY_ORDER)[number]

type DiscoveredJobRow = Awaited<ReturnType<typeof prisma.discoveredJob.findMany>>[number]

function asStringArray(value: unknown): string[] {
  return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : []
}

function hoursSince(date: Date | null | undefined): number | null {
  if (!date) return null
  return Math.max(0, Math.round((Date.now() - date.getTime()) / MS_PER_HOUR))
}

function seniorityFromTitle(title: string): Seniority | null {
  const value = title.toLowerCase()
  if (/\b(head|lead|principal|manager|director|vp)\b/.test(value)) return "lead"
  if (/\b(senior|sr\.?|staff)\b/.test(value)) return "senior"
  if (/\b(junior|jr\.?|intern|magang|entry|fresh)\b/.test(value)) return "entry"
  return null
}

/* ============================================================
 * Profil pencarian
 * ============================================================ */

function toProfileDto(profile: {
  id: string
  cvId: string
  cvVersion: number
  rolesJson: unknown
  skillsJson: unknown
  locationsJson: unknown
  industriesJson: unknown
  seniority: string | null
  remotePref: string
  yearsExp: number | null
  salaryMin: number | null
  salaryMax: number | null
  isAutoGenerated: boolean
}): SearchProfileDto {
  return {
    id: profile.id,
    cvId: profile.cvId,
    cvVersion: profile.cvVersion,
    roles: asStringArray(profile.rolesJson),
    skills: asStringArray(profile.skillsJson),
    locations: asStringArray(profile.locationsJson),
    industries: asStringArray(profile.industriesJson),
    seniority: (profile.seniority as SearchProfileDto["seniority"]) ?? null,
    remotePref: (profile.remotePref as SearchProfileDto["remotePref"]) ?? "any",
    yearsExp: profile.yearsExp,
    salaryMin: profile.salaryMin,
    salaryMax: profile.salaryMax,
    isAutoGenerated: profile.isAutoGenerated,
  }
}

async function loadCv(userId: string, cvId: string) {
  const cv = await prisma.cv.findFirst({
    where: { id: cvId, userId },
    select: { id: true, version: true, structuredJson: true, language: true },
  })
  if (!cv) throw new HttpError(404, "CV_NOT_FOUND", "CV tidak ditemukan")
  if (!cv.structuredJson || typeof cv.structuredJson !== "object") {
    throw new HttpError(400, "CV_NOT_PARSED", "CV ini belum selesai diproses")
  }
  return cv
}

/**
 * Profil di-cache per (user, cv, versi CV). Versi CV masuk kunci karena CV yang
 * sudah direvisi adalah CV yang berbeda — profil lama tidak boleh dipakai ulang
 * begitu saja.
 */
export async function getOrCreateSearchProfile(
  userId: string,
  cvId: string,
  overrides?: SearchProfileOverrides,
): Promise<SearchProfileDto> {
  const cv = await loadCv(userId, cvId)

  const existing = await prisma.jobSearchProfile.findUnique({
    where: { userId_cvId_cvVersion: { userId, cvId, cvVersion: cv.version } },
  })

  if (existing) {
    if (!overrides || Object.keys(overrides).length === 0) return toProfileDto(existing)
    const updated = await prisma.jobSearchProfile.update({
      where: { id: existing.id },
      data: {
        ...(overrides.roles ? { rolesJson: overrides.roles } : {}),
        ...(overrides.skills ? { skillsJson: overrides.skills } : {}),
        ...(overrides.locations ? { locationsJson: overrides.locations } : {}),
        ...(overrides.industries ? { industriesJson: overrides.industries } : {}),
        ...(overrides.remotePref ? { remotePref: overrides.remotePref } : {}),
        ...(overrides.seniority ? { seniority: overrides.seniority } : {}),
        ...(typeof overrides.salaryMin === "number" ? { salaryMin: overrides.salaryMin } : {}),
        isAutoGenerated: false,
      },
    })
    return toProfileDto(updated)
  }

  let draft
  try {
    draft = await generateSearchProfile({ cv: cv.structuredJson, language: cv.language })
  } catch (error) {
    console.error("[generateSearchProfile] Error detail:", error)
    throw new HttpError(
      502,
      "PROFILE_GENERATION_FAILED",
      "Gagal menyusun profil pencarian dari CV ini. Coba lagi sebentar lagi.",
    )
  }

  const created = await prisma.jobSearchProfile.create({
    data: {
      userId,
      cvId,
      cvVersion: cv.version,
      rolesJson: overrides?.roles ?? draft.roles,
      skillsJson: overrides?.skills ?? draft.skills,
      locationsJson: overrides?.locations ?? draft.locations,
      industriesJson: overrides?.industries ?? draft.industries,
      seniority: overrides?.seniority ?? draft.seniority,
      remotePref: overrides?.remotePref ?? draft.remotePref,
      yearsExp: draft.yearsExp,
      salaryMin: overrides?.salaryMin ?? null,
      isAutoGenerated: !overrides || Object.keys(overrides).length === 0,
      promptVersion: DISCOVERY_PROMPT_VERSION,
    },
  })

  return toProfileDto(created)
}

export async function updateSearchProfile(
  userId: string,
  profileId: string,
  input: UpdateSearchProfileInput,
): Promise<SearchProfileDto> {
  const existing = await prisma.jobSearchProfile.findFirst({
    where: { id: profileId, userId },
    select: { id: true },
  })
  if (!existing) throw new HttpError(404, "NOT_FOUND", "Profil pencarian tidak ditemukan")

  const updated = await prisma.jobSearchProfile.update({
    where: { id: profileId },
    data: {
      ...(input.roles ? { rolesJson: input.roles } : {}),
      ...(input.skills ? { skillsJson: input.skills } : {}),
      ...(input.locations ? { locationsJson: input.locations } : {}),
      ...(input.industries ? { industriesJson: input.industries } : {}),
      ...(input.remotePref ? { remotePref: input.remotePref } : {}),
      ...(input.seniority ? { seniority: input.seniority } : {}),
      ...(typeof input.salaryMin === "number" ? { salaryMin: input.salaryMin } : {}),
      isAutoGenerated: false,
    },
  })

  return toProfileDto(updated)
}

/* ============================================================
 * Retrieval dari indeks lokal
 * ============================================================ */

type RetrievalResult = {
  rows: DiscoveredJobRow[]
  relaxedFilters: string[]
}

async function retrieveCandidates(
  profile: SearchProfileDto,
  postedWithinDays: number,
): Promise<RetrievalResult> {
  const relaxedFilters: string[] = []
  const titleTerms = profile.roles.flatMap((role) =>
    role
      .toLowerCase()
      .split(/[^a-z0-9+#.]+/)
      .filter((token) => token.length >= 3),
  )
  const uniqueTerms = [...new Set(titleTerms)].slice(0, 12)

  const titleFilter =
    uniqueTerms.length > 0
      ? uniqueTerms.map((term) => ({ titleNorm: { contains: term } }))
      : undefined

  const cities = profile.locations.map((location) => location.trim()).filter(Boolean)

  const baseWhere = {
    expiresAt: { gt: new Date() },
    ...(postedWithinDays
      ? { OR: undefined, postedAt: { gte: new Date(Date.now() - postedWithinDays * MS_PER_DAY) } }
      : {}),
  }

  const query = async (where: Record<string, unknown>) =>
    prisma.discoveredJob.findMany({
      where,
      orderBy: [{ postedAt: "desc" }, { indexedAt: "desc" }],
      take: DISCOVERY_CANDIDATE_LIMIT,
    })

  const locationClause =
    cities.length > 0 && profile.remotePref !== "remote"
      ? {
          OR: [
            ...cities.map((city) => ({ city: { equals: city, mode: "insensitive" as const } })),
            { remoteType: "remote" },
          ],
        }
      : profile.remotePref === "remote"
        ? { remoteType: "remote" }
        : {}

  // Percobaan 1: judul + lokasi + jendela waktu.
  let rows = await query({
    ...baseWhere,
    ...(titleFilter ? { OR: titleFilter } : {}),
    ...(Object.keys(locationClause).length > 0 ? { AND: [locationClause] } : {}),
  })

  // Percobaan 2: buang filter lokasi. Lebih baik menampilkan lowongan di kota
  // lain dengan JUJUR bahwa lokasinya beda, daripada mengembalikan halaman kosong.
  if (rows.length < DISCOVERY_RELAX_THRESHOLD) {
    relaxedFilters.push("lokasi")
    rows = await query({
      ...baseWhere,
      ...(titleFilter ? { OR: titleFilter } : {}),
    })
  }

  // Percobaan 3: lebarkan jendela waktu posting.
  if (rows.length < DISCOVERY_RELAX_THRESHOLD) {
    relaxedFilters.push("tanggal posting")
    rows = await query({
      expiresAt: { gt: new Date() },
      ...(titleFilter ? { OR: titleFilter } : {}),
    })
  }

  return { rows, relaxedFilters }
}

/* ============================================================
 * Skor & ranking
 * ============================================================ */

function jobParsedFrom(row: DiscoveredJobRow) {
  const skills = asStringArray(row.skillTermsJson)
  return {
    jobTitle: row.title,
    company: row.company,
    level: seniorityFromTitle(row.title) ?? "",
    mustHaveSkills: skills.slice(0, 8),
    niceToHaveSkills: skills.slice(8, 14),
    requirements: [],
    keywords: skills,
  }
}

type ScoredCandidate = {
  row: DiscoveredJobRow
  score: number
  matchedSkills: string[]
  missingSkills: string[]
}

function scoreCandidate(
  row: DiscoveredJobRow,
  cvStructured: unknown,
  profile: SearchProfileDto,
): ScoredCandidate {
  const jobSkills = asStringArray(row.skillTermsJson)
  const profileSkills = profile.skills.map((skill) => skill.toLowerCase())
  const matchedSkills = jobSkills.filter((skill) => profileSkills.includes(skill.toLowerCase()))
  const missingSkills = jobSkills
    .filter((skill) => !profileSkills.includes(skill.toLowerCase()))
    .slice(0, 6)

  let score = 50
  try {
    // Mesin skor yang sama dengan fitur analisis — satu definisi "cocok" untuk
    // seluruh produk, supaya angka di dua halaman tidak saling membantah.
    score = ruleBasedScore(cvStructured as never, jobParsedFrom(row) as never).score
  } catch {
    score = jobSkills.length === 0 ? 50 : Math.round((matchedSkills.length / jobSkills.length) * 100)
  }

  // Penyesuaian ranking (PRD §12.3)
  if (row.primarySource.startsWith("ats:")) score += 5

  const postedAgeDays = row.postedAt ? (Date.now() - row.postedAt.getTime()) / MS_PER_DAY : null
  if (postedAgeDays !== null && postedAgeDays <= 7) score += 5
  if (postedAgeDays !== null && postedAgeDays > DISCOVERY_STALE_DAYS) score -= 10

  const cityMatch =
    row.city && profile.locations.some((loc) => loc.toLowerCase() === row.city?.toLowerCase())
  if (cityMatch) score += 5
  if (row.salaryMin || row.salaryMax) score += 3

  const jobSeniority = seniorityFromTitle(row.title)
  if (jobSeniority && profile.seniority) {
    const gap = Math.abs(
      SENIORITY_ORDER.indexOf(jobSeniority) -
        SENIORITY_ORDER.indexOf(profile.seniority as Seniority),
    )
    if (gap >= 2) score -= 15
  }

  return {
    row,
    score: Math.max(0, Math.min(100, Math.round(score))),
    matchedSkills,
    missingSkills,
  }
}

/* ============================================================
 * DTO
 * ============================================================ */

function toSourceDtos(row: DiscoveredJobRow): JobSourceDto[] {
  const raw = Array.isArray(row.sourcesJson) ? row.sourcesJson : []
  const sources = raw
    .map((entry) => entry as Record<string, unknown>)
    .filter((entry) => typeof entry.providerId === "string")
    .map((entry) => ({
      providerId: String(entry.providerId),
      displayName: String(entry.displayName ?? entry.providerId),
      url: String(entry.url ?? row.sourceUrl),
      applyUrl: String(entry.applyUrl ?? row.applyUrl),
      postedAt: typeof entry.postedAt === "string" ? entry.postedAt : null,
    }))

  if (sources.length > 0) return sources
  return [
    {
      providerId: row.primarySource,
      displayName: row.primarySource,
      url: row.sourceUrl,
      applyUrl: row.applyUrl,
      postedAt: row.postedAt?.toISOString() ?? null,
    },
  ]
}

function toJobMatchDto(
  match: {
    id: string
    rank: number
    isTopPick: boolean
    estimatedScore: number
    reasonText: string | null
    cautionText: string | null
    matchedSkillsJson: unknown
    missingSkillsJson: unknown
    status: string
  },
  row: DiscoveredJobRow,
): JobMatchDto {
  return {
    id: match.id,
    rank: match.rank,
    isTopPick: match.isTopPick,
    estimatedScore: match.estimatedScore,
    title: row.title,
    company: row.company,
    location: row.location,
    remoteType: (row.remoteType as JobMatchDto["remoteType"]) ?? null,
    salaryMin: row.salaryMin,
    salaryMax: row.salaryMax,
    currency: row.currency,
    salaryPeriod: row.salaryPeriod,
    reasonText: match.reasonText,
    cautionText: match.cautionText,
    matchedSkills: asStringArray(match.matchedSkillsJson),
    missingSkills: asStringArray(match.missingSkillsJson),
    sources: toSourceDtos(row),
    primarySource: row.primarySource,
    postedAt: row.postedAt?.toISOString() ?? null,
    postedHoursAgo: hoursSince(row.postedAt),
    indexedAt: row.indexedAt.toISOString(),
    indexedHoursAgo: hoursSince(row.indexedAt) ?? 0,
    isLikelyStale: row.isLikelyStale,
    status: match.status as JobMatchDto["status"],
  }
}

/* ============================================================
 * Pencarian
 * ============================================================ */

async function recordPendingQuery(
  userId: string,
  profile: SearchProfileDto,
): Promise<string | null> {
  const queryHash = createHash("sha256")
    .update([profile.roles.join(","), profile.locations.join(","), profile.remotePref].join("|"))
    .digest("hex")

  // Pencarian tanpa hasil bukan kegagalan yang dibuang — ini daftar permintaan
  // pasar yang menentukan perusahaan/kota mana yang layak diindeks berikutnya.
  const pending = await prisma.pendingQuery.upsert({
    where: { queryHash },
    create: {
      queryHash,
      userId,
      rolesJson: profile.roles,
      locationsJson: profile.locations,
      remotePref: profile.remotePref,
    },
    update: { requestCount: { increment: 1 }, lastRequestedAt: new Date() },
    select: { id: true },
  })
  return pending.id
}

export async function searchJobs(
  userId: string,
  input: DiscoverySearchInput,
): Promise<DiscoverySearchResponse> {
  const startedAt = Date.now()
  const entitlement = await checkDiscoveryEntitlement(userId)
  if (!entitlement.allowed) {
    throw new HttpError(
      429,
      "DISCOVERY_QUOTA_EXCEEDED",
      "Kuota pencarian lowongan gratis bulan ini telah habis",
    )
  }

  const cv = await loadCv(userId, input.cvId)
  const profile = await getOrCreateSearchProfile(userId, input.cvId, input.profileOverrides)
  const indexAgeHours = await getIndexAgeHours()

  const { rows, relaxedFilters } = await retrieveCandidates(profile, input.postedWithinDays ?? 30)

  // Indeks kosong sama sekali = masalah infrastruktur, bukan hasil pencarian nol.
  // User berhak tahu bedanya.
  if (indexAgeHours === null) {
    throw new HttpError(
      503,
      "INDEX_UNAVAILABLE",
      "Indeks lowongan belum siap. Coba lagi setelah proses pengumpulan lowongan berjalan.",
    )
  }

  const scored = rows
    .map((row) => scoreCandidate(row, cv.structuredJson, profile))
    .sort((a, b) => b.score - a.score)

  await consumeDiscoveryQuota(userId)

  if (scored.length === 0) {
    const pendingQueryId = await recordPendingQuery(userId, profile)
    const run = await prisma.jobDiscoveryRun.create({
      data: {
        userId,
        cvId: input.cvId,
        searchProfileId: profile.id,
        status: "EMPTY",
        candidateCount: 0,
        curatedCount: 0,
        indexAgeHours,
        relaxedFiltersJson: relaxedFilters,
        promptVersion: DISCOVERY_PROMPT_VERSION,
        latencyMs: Date.now() - startedAt,
      },
      select: { id: true },
    })

    return {
      runId: run.id,
      status: "EMPTY",
      searchProfile: profile,
      topPicks: [],
      otherCandidates: [],
      emptyState: {
        message: "Belum ada lowongan yang cocok di indeks kami saat ini",
        detail:
          "Indeks Dilirik baru mencakup halaman karier perusahaan pilihan dan sebagian portal lowongan — belum seluruh internet. Kami catat pencarian ini untuk menambah sumber baru.",
        canRequestAlert: true,
        pendingQueryId,
      },
      meta: {
        candidateCount: 0,
        indexAgeHours,
        indexIsPartial: relaxedFilters.length > 0,
        unavailableSources: [],
        relaxedFilters,
        quotaRemaining: entitlement.remaining === null ? null : Math.max(0, entitlement.remaining - 1),
        curationNote: null,
      },
    }
  }

  const forCuration = scored.slice(0, DISCOVERY_CURATION_INPUT)
  const candidates: CurationCandidate[] = forCuration.map((candidate, index) => ({
    index: index + 1,
    title: candidate.row.title,
    company: candidate.row.company,
    location: candidate.row.location,
    remoteType: candidate.row.remoteType,
    postedDaysAgo: candidate.row.postedAt
      ? Math.round((Date.now() - candidate.row.postedAt.getTime()) / MS_PER_DAY)
      : null,
    salaryText:
      candidate.row.salaryMin || candidate.row.salaryMax
        ? [candidate.row.salaryMin, candidate.row.salaryMax].filter(Boolean).join(" - ")
        : null,
    skillTerms: asStringArray(candidate.row.skillTermsJson),
    snippet: candidate.row.descriptionSnippet,
    sourceDisplayName: candidate.row.primarySource,
  }))

  let curation: Awaited<ReturnType<typeof curateTopPicks>> = {
    picks: [],
    note: null,
    usedFallback: true,
    rejectedCount: 0,
  }
  let curationFailed = false

  try {
    curation = await curateTopPicks({
      profileSummary: summarizeProfile(profile),
      profileTerms: [...profile.skills, ...profile.roles],
      candidates,
    })
  } catch {
    // Kurasi gagal bukan alasan menggagalkan pencarian. Hasil tetap ditampilkan
    // dengan urutan rule-based, hanya tanpa narasi "kenapa cocok".
    curationFailed = true
  }

  const pickByIndex = new Map(curation.picks.map((pick) => [pick.candidateIndex, pick]))
  const topIndexes = curation.usedFallback
    ? forCuration.slice(0, DISCOVERY_TOP_PICKS).map((_, index) => index + 1)
    : curation.picks.map((pick) => pick.candidateIndex)

  const status = curationFailed || relaxedFilters.length > 0 ? "PARTIAL" : "DONE"

  const run = await prisma.jobDiscoveryRun.create({
    data: {
      userId,
      cvId: input.cvId,
      searchProfileId: profile.id,
      status,
      candidateCount: scored.length,
      curatedCount: topIndexes.length,
      indexAgeHours,
      relaxedFiltersJson: relaxedFilters,
      curationNote: curation.note,
      promptVersion: DISCOVERY_PROMPT_VERSION,
      latencyMs: Date.now() - startedAt,
    },
    select: { id: true },
  })

  const topPicks: JobMatchDto[] = []
  const otherCandidates: JobMatchDto[] = []
  let rank = 0

  for (const [position, candidate] of scored
    .slice(0, DISCOVERY_CURATION_INPUT + DISCOVERY_OTHER_CANDIDATES)
    .entries()) {
    const candidateIndex = position + 1
    const isTopPick = topIndexes.includes(candidateIndex)
    const pick = pickByIndex.get(candidateIndex)

    if (!isTopPick && otherCandidates.length >= DISCOVERY_OTHER_CANDIDATES) continue

    rank++
    const match = await prisma.jobMatch.create({
      data: {
        userId,
        runId: run.id,
        discoveredJobId: candidate.row.id,
        rank,
        isTopPick,
        estimatedScore: candidate.score,
        reasonText: pick?.reasonText ?? null,
        cautionText: pick?.cautionText ?? null,
        matchedSkillsJson: candidate.matchedSkills,
        missingSkillsJson: candidate.missingSkills,
      },
      select: {
        id: true,
        rank: true,
        isTopPick: true,
        estimatedScore: true,
        reasonText: true,
        cautionText: true,
        matchedSkillsJson: true,
        missingSkillsJson: true,
        status: true,
      },
    })

    const dto = toJobMatchDto(match, candidate.row)
    if (isTopPick) topPicks.push(dto)
    else otherCandidates.push(dto)
  }

  return {
    runId: run.id,
    status,
    searchProfile: profile,
    topPicks,
    otherCandidates,
    meta: {
      candidateCount: scored.length,
      indexAgeHours,
      indexIsPartial: relaxedFilters.length > 0,
      unavailableSources: [],
      relaxedFilters,
      quotaRemaining:
        entitlement.remaining === null ? null : Math.max(0, entitlement.remaining - 1),
      curationNote: curation.note,
    },
  }
}

/* ============================================================
 * Riwayat & aksi pada hasil
 * ============================================================ */

export async function listRuns(userId: string): Promise<DiscoveryRunListItemDto[]> {
  const runs = await prisma.jobDiscoveryRun.findMany({
    where: { userId },
    orderBy: { createdAt: "desc" },
    take: 20,
  })
  return runs.map((run) => ({
    id: run.id,
    cvId: run.cvId,
    status: run.status as DiscoveryRunListItemDto["status"],
    candidateCount: run.candidateCount,
    curatedCount: run.curatedCount,
    indexAgeHours: run.indexAgeHours,
    createdAt: run.createdAt.toISOString(),
  }))
}

export async function getRun(userId: string, runId: string) {
  const run = await prisma.jobDiscoveryRun.findFirst({
    where: { id: runId, userId },
    include: {
      matches: { orderBy: { rank: "asc" }, include: { discoveredJob: true } },
      searchProfile: true,
    },
  })
  if (!run) throw new HttpError(404, "NOT_FOUND", "Riwayat pencarian tidak ditemukan")

  const matches = run.matches.map((match) => toJobMatchDto(match, match.discoveredJob))
  return {
    runId: run.id,
    status: run.status,
    createdAt: run.createdAt.toISOString(),
    searchProfile: run.searchProfile ? toProfileDto(run.searchProfile) : null,
    topPicks: matches.filter((match) => match.isTopPick),
    otherCandidates: matches.filter((match) => !match.isTopPick),
    meta: {
      candidateCount: run.candidateCount,
      indexAgeHours: run.indexAgeHours,
      curationNote: run.curationNote,
    },
  }
}

async function loadMatch(userId: string, matchId: string) {
  const match = await prisma.jobMatch.findFirst({
    where: { id: matchId, userId },
    include: { discoveredJob: true },
  })
  if (!match) throw new HttpError(404, "NOT_FOUND", "Lowongan tidak ditemukan")
  return match
}

export async function saveMatch(userId: string, matchId: string): Promise<JobMatchDto> {
  const match = await loadMatch(userId, matchId)
  const updated = await prisma.jobMatch.update({
    where: { id: match.id },
    data: { status: "SAVED" },
  })
  return toJobMatchDto(updated, match.discoveredJob)
}

export async function unsaveMatch(userId: string, matchId: string): Promise<JobMatchDto> {
  const match = await loadMatch(userId, matchId)
  const updated = await prisma.jobMatch.update({
    where: { id: match.id },
    data: { status: "NEW" },
  })
  return toJobMatchDto(updated, match.discoveredJob)
}

export async function dismissMatch(
  userId: string,
  matchId: string,
  input: DismissJobMatchInput,
): Promise<JobMatchDto> {
  const match = await loadMatch(userId, matchId)
  const updated = await prisma.jobMatch.update({
    where: { id: match.id },
    data: {
      status: "DISMISSED",
      dismissReason: input.reason,
      dismissNote: input.note ?? null,
    },
  })
  return toJobMatchDto(updated, match.discoveredJob)
}

export async function undismissMatch(userId: string, matchId: string): Promise<JobMatchDto> {
  const match = await loadMatch(userId, matchId)
  const updated = await prisma.jobMatch.update({
    where: { id: match.id },
    data: {
      status: "NEW",
      dismissReason: null,
      dismissNote: null,
    },
  })
  return toJobMatchDto(updated, match.discoveredJob)
}

/**
 * Menyiapkan analisis penuh: snippet lowongan dijadikan JobPosting milik user,
 * lalu alur analisis yang SUDAH ADA yang mengerjakan sisanya. Sengaja tidak
 * menduplikasi analysisService — satu mesin analisis untuk seluruh produk.
 *
 * Catatan yang harus jujur ke user: yang tersimpan hanya ringkasan, jadi analisis
 * berbasis snippet bisa kurang lengkap dibanding menempel deskripsi penuh.
 */
export async function prepareMatchAnalysis(
  userId: string,
  matchId: string,
): Promise<{ jobPostingId: string; matchId: string; usedSnippet: boolean }> {
  const match = await loadMatch(userId, matchId)
  if (match.jobPostingId) {
    return { jobPostingId: match.jobPostingId, matchId: match.id, usedSnippet: true }
  }

  const job = match.discoveredJob
  const rawText = [
    `${job.title} — ${job.company}`,
    job.location ? `Lokasi: ${job.location}` : null,
    job.remoteType ? `Tipe kerja: ${job.remoteType}` : null,
    "",
    job.descriptionSnippet,
    "",
    `Sumber: ${job.primarySource}`,
    `Tautan: ${job.applyUrl}`,
  ]
    .filter((line) => line !== null)
    .join("\n")

  const jobPosting = await prisma.jobPosting.create({
    data: {
      userId,
      sourceUrl: job.applyUrl,
      rawText,
      parsedJson: jobParsedFrom(job),
    },
    select: { id: true },
  })

  await prisma.jobMatch.update({
    where: { id: match.id },
    data: { status: "ANALYZED", jobPostingId: jobPosting.id },
  })

  return { jobPostingId: jobPosting.id, matchId: match.id, usedSnippet: true }
}

export async function requestAlert(userId: string, pendingQueryId: string): Promise<void> {
  const pending = await prisma.pendingQuery.findUnique({
    where: { id: pendingQueryId },
    select: { id: true },
  })
  if (!pending) throw new HttpError(404, "NOT_FOUND", "Permintaan pencarian tidak ditemukan")
  await prisma.pendingQuery.update({
    where: { id: pending.id },
    data: { alertRequested: true, userId },
  })
}

export async function getDiscoveryStatus(userId: string): Promise<DiscoveryStatusDto> {
  const [jobCount, indexAgeHours, lastIngestion, entitlement] = await Promise.all([
    prisma.discoveredJob.count({ where: { expiresAt: { gt: new Date() } } }),
    getIndexAgeHours(),
    prisma.ingestionRun.findFirst({
      orderBy: { startedAt: "desc" },
      select: { status: true, providerStatsJson: true },
    }),
    checkDiscoveryEntitlement(userId),
  ])

  const stats = Array.isArray(lastIngestion?.providerStatsJson)
    ? (lastIngestion.providerStatsJson as Array<Record<string, unknown>>)
    : []

  return {
    indexJobCount: jobCount,
    indexAgeHours,
    lastIngestionStatus: lastIngestion?.status ?? null,
    unavailableSources: stats
      .filter((stat) => stat.status === "DISABLED" || stat.status === "ERROR")
      .map((stat) => String(stat.providerId)),
    quota: {
      quota: entitlement.quota,
      used: entitlement.used,
      remaining: entitlement.remaining,
      resetAt: entitlement.resetAt.toISOString(),
    },
  }
}
